.PHONY: all
all:
	$(MAKE) -C localization $@
	$(MAKE) -C strategy $@
	$(MAKE) -C movement $@
	$(MAKE) -C util $@

.PHONY: clean
clean:
	$(MAKE) -C localization $@
	$(MAKE) -C strategy $@
	$(MAKE) -C movement $@
	$(MAKE) -C util $@

.PHONY: test
test:
	$(MAKE) -C localization $@
	$(MAKE) -C strategy $@
	$(MAKE) -C movement $@
	$(MAKE) -C util $@
