/* strategy_test_data.h */

#ifndef _STRATEGY_TEST_DATA_H_
#define _STRATEGY_TEST_DATA_H_


#define size 16*2+1


const char* empty_string[size] = {
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "X                               X",
    "X X X X X X X X X X X X X X X X X",
    "X                               X",
    "X X X X X X X X X X X X X X X X X",
    "X                               X",
    "X X X X X X X X X X X X X X X X X",
    "X                               X",
    "X X X X X X X X X X X X X X X X X",
    "X                               X",
    "X X X X X X X X X X X X X X X X X",
    "X                               X",
    "X X X X X X X X X X X X X X X X X",
    "X                               X",
    "X X X X X X X X X X X X X X X X X",
    "X                               X",
    "X X X X X X X X X X X X X X X X X",
    "X                               X",
    "X X X X X X X X X X X X X X X X X",
    "X                               X",
    "X X X X X X X X X X X X X X X X X",
    "X                               X",
    "X X X X X X X X X X X X X X X X X",
    "X                               X",
    "X X X X X X X X X X X X X X X X X",
    "X                               X",
    "X X X X X X X X X X X X X X X X X",
    "X                               X",
    "X X X X X X X X X X X X X X X X X",
    "X                               X",
    "X X X X X X X X X X X X X X X X X",
    "X                               X",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
};


const char* spiral_string[size] = {
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "X                               X",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X",
    "X                             X X",
    "X XXXXXXXXXXXXXXXXXXXXXXXXXXX X X",
    "X X                         X X X",
    "X X XXXXXXXXXXXXXXXXXXXXXXX X X X",
    "X X X                     X X X X",
    "X X X XXXXXXXXXXXXXXXXXXX X X X X",
    "X X X X                 X X X X X",
    "X X X X XXXXXXXXXXXXXXX X X X X X",
    "X X X X X             X X X X X X",
    "X X X X X XXXXXXXXXXX X X X X X X",
    "X X X X X X         X X X X X X X",
    "X X X X X X XXXXXXX X X X X X X X",
    "X X X X X X X     X X X X X X X X",
    "X X X X X X X XXX X X X X X X X X",
    "X X X X X X X X   X X X X X X X X",
    "X X X X X X X XXXXX X X X X X X X",
    "X X X X X X X       X X X X X X X",
    "X X X X X X XXXXXXXXX X X X X X X",
    "X X X X X X           X X X X X X",
    "X X X X X XXXXXXXXXXXXX X X X X X",
    "X X X X X               X X X X X",
    "X X X X XXXXXXXXXXXXXXXXX X X X X",
    "X X X X                   X X X X",
    "X X X XXXXXXXXXXXXXXXXXXXXX X X X",
    "X X X                       X X X",
    "X X XXXXXXXXXXXXXXXXXXXXXXXXX X X",
    "X X                           X X",
    "X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X",
    "X                               X",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
};


const char* loop_string[size] = {
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "X                               X",
    "X XXX XXX XXX XXX XXX XXX XXX X X",
    "X X X X X X X X X X X X X X X   X",
    "X XXX XXX XXX XXX XXX XXX XXX X X",
    "X                               X",
    "X X XXX XXX XXX XXX XXX XXX XXX X",
    "X   X X X X X X X X X X X X X X X",
    "X X XXX XXX XXX XXX XXX XXX XXX X",
    "X                               X",
    "X XXX XXX XXX XXX XXX XXX XXX X X",
    "X X X X X X X X X X X X X X X   X",
    "X XXX XXX XXX XXX XXX XXX XXX X X",
    "X                               X",
    "X X XXX XXX XXX XXX XXX XXX XXX X",
    "X   X X X X X X X X X X X X X X X",
    "X X XXX XXX XXX XXX XXX XXX XXX X",
    "X                               X",
    "X XXX XXX XXX XXX XXX XXX XXX X X",
    "X X X X X X X X X X X X X X X   X",
    "X XXX XXX XXX XXX XXX XXX XXX X X",
    "X                               X",
    "X X XXX XXX XXX XXX XXX XXX XXX X",
    "X   X X X X X X X X X X X X X X X",
    "X X XXX XXX XXX XXX XXX XXX XXX X",
    "X                               X",
    "X XXX XXX XXX XXX XXX XXX XXX X X",
    "X X X X X X X X X X X X X X X   X",
    "X XXX XXX XXX XXX XXX XXX XXX X X",
    "X                               X",
    "X XXX XXX XXX XXX XXX XXX XXX X X",
    "X X X X X X X X X X X X X X X   X",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
};


const char* actual_string[size] = {
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "X   X     X   X     X           X",
    "XXX X XXX X X X XXXXX X XXXXXXX X",
    "X   X   X   X X X     X   X X   X",
    "X XXXXX XXXXX X X XXXXX X X X XXX",
    "X     X X   X   X     X X X   X X",
    "XXXXX X XXX X XXXXXXX X X X XXX X",
    "X   X     X     X   X X X X     X",
    "X X XXX X X XXXXX X XXX X XXXXXXX",
    "X X     X X X     X     X X   X X",
    "X XXXXX X X X XXX XXXXXXX XXX X X",
    "X     X X X   X X X   X X X   X X",
    "XXXXX X X XXXXX X X X X X X XXX X",
    "X     X X   X X X   X X X   X   X",
    "X XXXXXXXXX X XXXXXXX X XXX X XXX",
    "X   X X   X   X   X   X   X   X X",
    "XXX X X X X X X X X XXXXX XXXXX X",
    "X X X   X   X X   X     X     X X",
    "X X XXXXX XXXXX XXXXX X X XXX X X",
    "X   X   X     X X     X   X X   X",
    "XXXXXXX XXXXXXX XXXXX X XXX X X X",
    "X       X   X   X     X   X   X X",
    "X X XXXXX X X XXX X XXXXX XXXXX X",
    "X X       X   X X X X   X     X X",
    "X XXXXXXXXX XXX X X XXX XXXXXXX X",
    "X   X       X X   X X   X   X   X",
    "XXX X XXXXXXX XXXXX X XXXXX X XXX",
    "X X X   X   X       X X     X   X",
    "X X XXX XXX XXXXXXXXX X XXX XXX X",
    "X X X   X     X   X     X   X   X",
    "X X X XXX X X X X X X XXX XXX XXX",
    "X   X     X X   X   X   X       X",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
};

#endif //_STRATEGY_TEST_DATA_H_
